# Generated by Django 4.0.5 on 2022-12-09 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_alter_freequote_date_posted_alter_quote_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freequote',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 9, 17, 10, 25, 835991), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 835991)),
        ),
    ]
