# Generated by Django 4.0.5 on 2022-12-14 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_alter_freequote_date_posted_alter_quote_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freequote',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 14, 12, 25, 30, 63770), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 12, 25, 30, 62777)),
        ),
    ]
