# Generated by Django 4.0.5 on 2022-12-18 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_alter_freequote_date_posted_alter_quote_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freequote',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 18, 13, 13, 11, 529478), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 13, 13, 11, 529478)),
        ),
    ]
