# Generated by Django 4.0.5 on 2022-12-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africanews', '0004_alter_africanews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africanews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 16, 33, 59, 851293)),
        ),
        migrations.AlterField(
            model_name='africanews',
            name='published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
