# Generated by Django 4.0.5 on 2022-12-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldnews', '0006_alter_worldnews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldnews',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 16, 33, 59, 835673)),
        ),
    ]
