# Generated by Django 4.0.5 on 2022-12-09 16:10

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kingnze', '0002_health_headline_environment_crime_bigstory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 820350)),
        ),
        migrations.AlterField(
            model_name='crime',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 820350)),
        ),
        migrations.AlterField(
            model_name='environment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 820350)),
        ),
        migrations.AlterField(
            model_name='headline',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 820350)),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 820350)),
        ),
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=False, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 12, 9, 17, 10, 25, 820350))),
                ('leadimg', models.ImageField(upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trending',
                'verbose_name_plural': 'Trending',
                'db_table': 'Trending',
                'managed': True,
            },
        ),
    ]
