# Generated by Django 4.0.5 on 2022-12-19 00:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kingnze', '0006_comment_alter_bigstory_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 747328)),
        ),
        migrations.AlterField(
            model_name='business',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 747328)),
        ),
        migrations.AlterField(
            model_name='crime',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 747328)),
        ),
        migrations.AlterField(
            model_name='environment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 747328)),
        ),
        migrations.AlterField(
            model_name='headline',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 742345)),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 747328)),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 752321)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 54, 53, 752321)),
        ),
        migrations.CreateModel(
            name='Commet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kingnze.bigstory')),
                ('usercommet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commet',
                'verbose_name_plural': 'Commets',
                'db_table': 'commets',
                'managed': True,
            },
        ),
    ]
