# Generated by Django 4.0.5 on 2022-12-19 14:26

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kingnze', '0008_alter_bigstory_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 436469))),
                ('leadimg', models.ImageField(upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Politics',
                'verbose_name_plural': 'Politics',
                'db_table': 'Politics',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='bigstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 441461)),
        ),
        migrations.AlterField(
            model_name='business',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 436469)),
        ),
        migrations.AlterField(
            model_name='crime',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 441461)),
        ),
        migrations.AlterField(
            model_name='environment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 441461)),
        ),
        migrations.AlterField(
            model_name='headline',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 431451)),
        ),
        migrations.AlterField(
            model_name='health',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 446434)),
        ),
        migrations.AlterField(
            model_name='tech',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 446434)),
        ),
        migrations.AlterField(
            model_name='trending',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 15, 26, 16, 446434)),
        ),
        migrations.CreateModel(
            name='PoliticsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('Politicsusercomment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kingnze.politics')),
            ],
            options={
                'verbose_name': 'PoliticsComment',
                'verbose_name_plural': 'PoliticsComments',
                'db_table': 'PoliticsComments',
                'managed': True,
            },
        ),
    ]
