# Generated by Django 4.0.5 on 2022-12-18 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0008_alter_entertainment_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 13, 13, 11, 513850)),
        ),
    ]
